---
title: Let's Code
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: thiago_melo1993@hotmail.com
description: |-
  Sou apaixonado por inovação, criatividade e por desenvolvimento de sistemas. Gosto de participar de todas as fases do desenvolvimento, desde a concepção da ideia até a codificação em si.

   Estou constantemente à procura de novas tecnologias, ferramentas e metodologias para melhorar a mim mesmo.

   Eu posso facilmente aprender novos frameworks e atualmente estou aprendendo Go, jekyll e DynamoDB

   Don't stop learning.
baseurl: "/lets-code-blog"
url: https://rdpodcasting.github.io
twitter_username: Thiago_Roock
github_username: RDPodcasting
markdown: kramdown
permalink: "/:title"
theme: minima
plugins:
- jekyll-feed
